---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# components:
#   - ../../components/common
resources:
  - ./namespace.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kubernetes-dashboard/ks.yaml
  - ./gatus/ks.yaml
  - ./loki/ks.yaml
  - ./unpoller/ks.yaml
  - ./promtail/ks.yaml
  - ./blackbox-exporter/ks.yaml
